services:
  eldes-alice:
    image: ${DOCKER_USERNAME}/eldes-alice:${TAG}
    container_name: eldes-alice
    restart: always
    environment:
      TZ: Europe/Moscow
      ELDES_API_BASE_URL: ${ELDES_API_BASE_URL}
      ELDES_API_EMAIL: ${ELDES_API_EMAIL}
      ELDES_API_PASSWORD: ${ELDES_API_PASSWORD}
    volumes:
      - ./logs:/app/logs
    ports:
      - "8081:8081"
    env_file:
      - .env
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.eldes-alice.rule=Host(`eldes-alice.housekpr.ru`)"
    networks:
      - housekpr-network

networks:
  housekpr-network:
    external: true
