services:
  eldes-alice:
    image: ${DOCKER_USERNAME}/eldes-alice:${TAG}
    container_name: eldes-alice
    restart: always
    environment:
      TZ: Europe/Moscow
      ELDES_API_BASE_URL: ${ELDES_API_BASE_URL}
      ELDES_API_EMAIL: ${ELDES_API_EMAIL}
      ELDES_API_PASSWORD: ${ELDES_API_PASSWORD}
      SMART_HOME_OAUTH_CLIENT_ID: ${SMART_HOME_OAUTH_CLIENT_ID}
      SMART_HOME_OAUTH_CLIENT_SECRET: ${SMART_HOME_OAUTH_CLIENT_SECRET}
    volumes:
      - ./logs:/app/logs
    ports:
      - "8081:8081"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sim-sim.rule=Host(`sim-sim.housekpr.ru`)"
    networks:
      - housekpr-network

networks:
  housekpr-network:
    external: true
